// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Escolha como deseja integrar',
      description: 'Integração via REST API',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'category',
          label: '🌐 Sistemas WEB e SaaS',
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'integracoes/integracao-via-api' },
          ],
        },
        {
          type: 'category',
          label: '🖥 Sistemas Desktop',
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'integracoes/integracao-via-api-local-pos' },
          ],
        },
        {
          type: 'category',
          label: '🔄 Outras Integrações',
          collapsed: true,
          items: [
            {
              type: 'category', label: '📱 Android', items: [
                { type: 'autogenerated', dirName: 'integracoes/integracao-via-intent-android' }
              ]
            },
            {
              type: 'category',
              label: '🏛️ Sistemas Legados',
              collapsed: true,
              items: [
                {
                  type: 'category', label: '📁 Troca de arquivos', items: [
                    { type: 'autogenerated', dirName: 'integracoes/integracao-via-troca-arquivos' }
                  ]
                },
                { type: 'autogenerated', dirName: 'integracoes/sitef' },
                { type: 'autogenerated', dirName: 'integracoes/elgin' },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guia de ativação',
      collapsed: true,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'guia-ativacao' }],
    },
    {
      type: 'category',
      label: 'Resolvendo problemas na implantação',
      collapsed: true,
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'duvidas' }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
