// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Integrações',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'category',
          label: '🌐 Sistemas Web e SaaS',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-api'},
          ],
        },
        {
          type: 'category',
          label: '🖥 Sistemas Desktop',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-api-local-gp'},
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-dll'},
          ],
        },
        {
          type: 'category',
          label: '📱 Aplicações Android',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-api-local-pos'},
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-sdk-android'},
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-intent-android'},
          ],
        },
        {
          type: 'category',
          label: '🔄 Migração e Sistemas Legados',
          collapsed: true,
          items: [
            {type: 'autogenerated', dirName: 'integracoes/integracao-via-troca-arquivos'},
            {type: 'autogenerated', dirName: 'integracoes/sitef'},
            {type: 'autogenerated', dirName: 'integracoes/elgin'},
          ],
        },
      ],
    },
    {type: 'autogenerated', dirName: 'guia-ativacao'},
    {type: 'autogenerated', dirName: 'duvidas'},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
